CREATE TABLE `DUNGEON`
(
  `guildID` INTEGER PRIMARY KEY,
  `town_channel` INTEGER,
  `dungeon_channel` INTEGER,
  `partyID` INTEGER,
  `dungeon_type` TEXT,
  `mission` TEXT
);

CREATE TABLE `ITEM_LIST`
(
  `itemID` INTEGER PRIMARY KEY,
  `name` TEXT UNIQUE NOT NULL,
  `cost` INTEGER NOT NULL,
  `stack_size` INTEGER NOT NULL,
  `type` TEXT NOT NULL
);

CREATE TABLE `TRINKET_LIST`
(
  `trinketID` INTEGER PRIMARY KEY,
  `itemID` INTEGER NOT NULL,
  `trinketName` TEXT
);

CREATE TABLE `TRINKET_EFFECT`
(
  `trinketID` INTEGER,
  `stat` TEXT NOT NULL,
  `modifier` INTEGER NOT NULL
);

CREATE TABLE `ADVENTURER_LIST`
(
  `advID` INTEGER PRIMARY KEY,
  `class` TEXT UNIQUE NOT NULL,
  `max_hp` INTEGER NOT NULL,
  `dodge` INTEGER NOT NULL,
  `prot` INTEGER NOT NULL,
  `spd` INTEGER NOT NULL,
  `acc` INTEGER NOT NULL,
  `crit` INTEGER NOT NULL,
  `dmg_lower` INTEGER NOT NULL,
  `dmg_upper` INTEGER NOT NULL,
  `stun_res` INTEGER NOT NULL,
  `blight_res` INTEGER NOT NULL,
  `disease_res` INTEGER NOT NULL,
  `death_blow_res` INTEGER NOT NULL,
  `move_res` INTEGER NOT NULL,
  `bleed_res` INTEGER NOT NULL,
  `debuff_res` INTEGER NOT NULL,
  `trap_res` INTEGER NOT NULL,
  `stress_res` INTEGER NOT NULL,
  `virtue_chance` INTEGER NOT NULL,
  `crit_bonus` TEXT NOT NULL
);

CREATE TABLE `MONSTER_LIST`
(
  `monsterID` INTEGER PRIMARY KEY,
  `name` TEXT UNIQUE NOT NULL,
  `max_hp` INTEGER NOT NULL,
  `dodge` INTEGER NOT NULL,
  `prot` INTEGER NOT NULL,
  `spd` INTEGER NOT NULL,
  `acc` INTEGER NOT NULL,
  `crit` INTEGER NOT NULL,
  `dmg_lower` INTEGER NOT NULL,
  `dmg_upper` INTEGER NOT NULL,
  `stun_res` INTEGER NOT NULL,
  `blight_res` INTEGER NOT NULL,
  `disease_res` INTEGER NOT NULL,
  `death_blow_res` INTEGER NOT NULL,
  `move_res` INTEGER NOT NULL,
  `bleed_res` INTEGER NOT NULL,
  `debuff_res` INTEGER NOT NULL,
  `trap_res` INTEGER NOT NULL
);

CREATE TABLE `EFFECT_LIST`
(
  `effectID` INTEGER PRIMARY KEY,
  `name` TEXT,
  `stat` TEXT
);

CREATE TABLE `SKILL_LIST`
(
  `skillID` INTEGER PRIMARY KEY,
  `range` TEXT,
  `rank` INTEGER,
  `target` INTEGER,
  `target_ally` BOOLEAN,
  `damage_mod` INTEGER,
  `accuracy_mod` INTEGER,
  `crit_mod` INTEGER
);

CREATE TABLE `SKILL_EFFECT`
(
  `skillID` INTEGER,
  `stat` TEXT,
  `modifier` INTEGER,
  `self` BOOLEAN
);

CREATE TABLE `QUIRK_LIST`
(
  `quirkID` INTEGER PRIMARY KEY,
  `name` TEXT,
  `stat` TEXT
);

CREATE TABLE `PLAYERS`
(
  `playerID` INTEGER PRIMARY KEY,
  `gold` INTEGER NOT NULL,
  `busts` INTEGER NOT NULL,
  `portraits` INTEGER NOT NULL,
  `deeds` INTEGER NOT NULL,
  `crests` INTEGER NOT NULL,
  `blacksmith_weapon_level` INTEGER NOT NULL,
  `blacksmith_armor_level` INTEGER NOT NULL,
  `blacksmith_discount_level` INTEGER NOT NULL,
  `guild_skill_level_cap` INTEGER NOT NULL,
  `guild_discount_level` INTEGER NOT NULL,
  `nomad_trinket_count` INTEGER NOT NULL,
  `nomad_discount_level` INTEGER NOT NULL,
  `sanitarium_discount_level` INTEGER NOT NULL,
  `stagecoach_size` INTEGER NOT NULL,
  `stagecoach_level_cap` INTEGER NOT NULL,
  `roster_size_level` INTEGER NOT NULL,
  `survivalist_discount_level` INTEGER NOT NULL
);

CREATE TABLE `TOWN_BASE_COST`
(
  `name` TEXT PRIMARY KEY,
  `busts` INTEGER NOT NULL,
  `portraits` INTEGER NOT NULL,
  `deeds` INTEGER NOT NULL,
  `crests` INTEGER NOT NULL
);

CREATE TABLE `TOWN_UPGRADE_COST`
(
  `name` TEXT PRIMARY KEY,
  `busts` INTEGER NOT NULL,
  `portraits` INTEGER NOT NULL,
  `deeds` INTEGER NOT NULL,
  `crests` INTEGER NOT NULL
);

CREATE TABLE `ADVENTURERS`
(
  `heroID` INTEGER PRIMARY KEY,
  `advID` INTEGER NOT NULL,
  `playerID` INTEGER NOT NULL,
  `name` TEXT NOT NULL,
  `level` INTEGER NOT NULL,
  `hp` INTEGER NOT NULL,
  `stress` INTEGER NOT NULL,
  `exp` INTEGER NOT NULL,
  `weapon_level` INTEGER NOT NULL,
  `armor_level` INTEGER NOT NULL,
  `status` TEXT NOT NULL DEFAULT 'ALIVE'
);

CREATE TABLE `STAGECOACH`
(
  `stagecoachID` INTEGER PRIMARY KEY,
  `playerID` INTEGER NOT NULL,
  `advID` INTEGER NOT NULL,
  `name` TEXT NOT NULL,
  `level` INTEGER NOT NULL,
  `time` INTEGER NOT NULL
);

CREATE TABLE `PARTY`
(
  `partyID` INTEGER PRIMARY KEY,
  `leaderID` INTEGER NOT NULL,
  `pos1` INTEGER NOT NULL,
  `pos2` INTEGER NOT NULL,
  `pos3` INTEGER NOT NULL,
  `pos4` INTEGER NOT NULL
);

CREATE TABLE `ROOM`
(
  `roomID` INTEGER PRIMARY KEY,
  `guildID` INTEGER,
  `room` BOOLEAN,
  `type` TEXT
);

CREATE TABLE `ROOM_ENEMY`
(
  `roomID` INTEGER,
  `monsterID` INTEGER
);

CREATE TABLE `ROOM_TREASURE`
(
  `roomID` INTEGER,
  `itemID` INTEGER
);

CREATE TABLE `QUIRKS`
(
  `quirkID` INTEGER NOT NULL,
  `heroID` INTEGER NOT NULL,
  `modifier` INTEGER
);

CREATE TABLE `INVENTORY`
(
  `itemID` INTEGER NOT NULL,
  `playerID` INTEGER NOT NULL
);

CREATE TABLE `TRINKETS`
(
  `heroID` INTEGER NOT NULL,
  `slot1` INTEGER,
  `slot2` INTEGER
);

CREATE TABLE `SKILLS`
(
  `skillID` INTEGER NOT NULL,
  `heroID` INTEGER NOT NULL
);

CREATE TABLE `EFFECTS`
(
  `effectID` INTEGER NOT NULL,
  `heroID` INTEGER NOT NULL,
  `stat` TEXT,
  `modifier` INTEGER,
  `duration` INTEGER
);

ALTER TABLE `STAGECOACH` ADD FOREIGN KEY (`advID`) REFERENCES `ADVENTURER_LIST` (`advID`);

ALTER TABLE `STAGECOACH` ADD FOREIGN KEY (`playerID`) REFERENCES `PLAYERS` (`playerID`);

ALTER TABLE `QUIRKS` ADD FOREIGN KEY (`quirkID`) REFERENCES `QUIRK_LIST` (`quirkID`);

ALTER TABLE `SKILLS` ADD FOREIGN KEY (`skillID`) REFERENCES `SKILL_LIST` (`skillID`);

ALTER TABLE `SKILLS` ADD FOREIGN KEY (`heroID`) REFERENCES `ADVENTURERS` (`heroID`);

ALTER TABLE `QUIRKS` ADD FOREIGN KEY (`heroID`) REFERENCES `ADVENTURERS` (`heroID`);

ALTER TABLE `INVENTORY` ADD FOREIGN KEY (`playerID`) REFERENCES `PLAYERS` (`playerID`);

ALTER TABLE `SKILL_EFFECT` ADD FOREIGN KEY (`skillID`) REFERENCES `SKILL_LIST` (`skillID`);

ALTER TABLE `ROOM` ADD FOREIGN KEY (`guildID`) REFERENCES `DUNGEON` (`guildID`);

ALTER TABLE `ROOM_ENEMY` ADD FOREIGN KEY (`roomID`) REFERENCES `ROOM` (`roomID`);

ALTER TABLE `ROOM_TREASURE` ADD FOREIGN KEY (`roomID`) REFERENCES `ROOM` (`roomID`);

ALTER TABLE `ROOM_TREASURE` ADD FOREIGN KEY (`itemID`) REFERENCES `ITEM_LIST` (`itemID`);

ALTER TABLE `ROOM_ENEMY` ADD FOREIGN KEY (`monsterID`) REFERENCES `MONSTER_LIST` (`monsterID`);

ALTER TABLE `EFFECTS` ADD FOREIGN KEY (`effectID`) REFERENCES `EFFECT_LIST` (`effectID`);

ALTER TABLE `EFFECTS` ADD FOREIGN KEY (`heroID`) REFERENCES `ADVENTURERS` (`heroID`);

ALTER TABLE `INVENTORY` ADD FOREIGN KEY (`itemID`) REFERENCES `ITEM_LIST` (`itemID`);

ALTER TABLE `PARTY` ADD FOREIGN KEY (`leaderID`) REFERENCES `PLAYERS` (`playerID`);

ALTER TABLE `DUNGEON` ADD FOREIGN KEY (`partyID`) REFERENCES `PARTY` (`partyID`);

ALTER TABLE `PARTY` ADD FOREIGN KEY (`pos1`) REFERENCES `ADVENTURERS` (`heroID`);

ALTER TABLE `PARTY` ADD FOREIGN KEY (`pos2`) REFERENCES `ADVENTURERS` (`heroID`);

ALTER TABLE `PARTY` ADD FOREIGN KEY (`pos3`) REFERENCES `ADVENTURERS` (`heroID`);

ALTER TABLE `PARTY` ADD FOREIGN KEY (`pos4`) REFERENCES `ADVENTURERS` (`heroID`);

ALTER TABLE `TRINKETS` ADD FOREIGN KEY (`heroID`) REFERENCES `ADVENTURERS` (`heroID`);

ALTER TABLE `TRINKETS` ADD FOREIGN KEY (`slot1`) REFERENCES `TRINKET_LIST` (`trinketID`);

ALTER TABLE `TRINKETS` ADD FOREIGN KEY (`slot2`) REFERENCES `TRINKET_LIST` (`trinketID`);

ALTER TABLE `TRINKET_LIST` ADD FOREIGN KEY (`itemID`) REFERENCES `ITEM_LIST` (`itemID`);

ALTER TABLE `TRINKET_EFFECT` ADD FOREIGN KEY (`trinketID`) REFERENCES `TRINKET_LIST` (`trinketID`);
